# Generated by Django 2.2 on 2019-04-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.FileField(null=True, upload_to='question/'),
        ),
    ]
