# Generated by Django 2.2 on 2019-04-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.FileField(blank=True, default=1, upload_to='question/'),
            preserve_default=False,
        ),
    ]
