# Generated by Django 2.2 on 2019-04-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190410_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_img',
            field=models.FileField(blank=True, null=True, upload_to='question/'),
        ),
    ]
