# Generated by Django 2.2 on 2019-04-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20190410_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_img',
            field=models.FileField(blank=True, default=1, upload_to='question/'),
            preserve_default=False,
        ),
    ]
