# Generated by Django 2.2 on 2019-04-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20190411_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_img',
            field=models.FileField(null=True, upload_to='question/'),
        ),
    ]
