# Generated by Django 2.2 on 2019-04-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20190413_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='like_view',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
