# Generated by Django 2.2 on 2019-04-13 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20190413_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='like_view',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
