# Generated by Django 2.2 on 2019-04-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_like_view_uploaded_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
