# Generated by Django 2.2 on 2019-04-20 20:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20190417_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topics',
            field=models.CharField(choices=[('Mobility', 'Mobility'), ('Hardware', 'Hardware'), ('Gamming', 'Gamming'), ('Security', 'Security'), ('Internet', 'Internet'), ('Software', 'Software')], default='Mobility', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='Interest',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mobility', 'Mobility'), ('Hardware', 'Hardware'), ('Gamming', 'Gamming'), ('Security', 'Security'), ('Internet', 'Internet'), ('Software', 'Software')], default='Computer', max_length=300, verbose_name='Select your interested topics'),
        ),
    ]
