# Generated by Django 2.2 on 2019-04-21 07:06

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20190420_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topics',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mobility', 'Mobility'), ('Hardware', 'Hardware'), ('Gamming', 'Gamming'), ('Security', 'Security'), ('Internet', 'Internet'), ('Software', 'Software')], default='Computer', max_length=300, verbose_name='Select your interested topics'),
        ),
    ]
