# Generated by Django 2.2 on 2019-04-22 09:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20190421_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topics',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Smartphone', 'Smartphone'), ('Hardware', 'Hardware'), ('Gamming', 'Gamming'), ('Security', 'Security'), ('Internet', 'Internet'), ('Software', 'Software')], default='Computer', max_length=300, verbose_name='Select your interested topics'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Interest',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Smartphone', 'Smartphone'), ('Hardware', 'Hardware'), ('Gamming', 'Gamming'), ('Security', 'Security'), ('Internet', 'Internet'), ('Software', 'Software')], default='Computer', max_length=300, verbose_name='Select your interested topics'),
        ),
    ]
