# Generated by Django 2.2 on 2019-04-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_auto_20190422_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_img',
            field=models.ImageField(blank=True, null=True, upload_to='answer/'),
        ),
    ]
