# Generated by Django 2.2 on 2019-05-22 16:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_answer_answer_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topics',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Smartphone', 'Smartphone'), ('Hardware', 'Hardware'), ('Gamming', 'Gamming'), ('Security', 'Security'), ('Internet', 'Internet'), ('Software and App', 'Software and App')], max_length=300, verbose_name='Select your interested topics'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Interest',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Smartphone', 'Smartphone'), ('Hardware', 'Hardware'), ('Gamming', 'Gamming'), ('Security', 'Security'), ('Internet', 'Internet'), ('Software and App', 'Software and App')], max_length=300, verbose_name='Select your interested topics'),
        ),
    ]
